config/routes.rb
Pharmacy::Application.routes.draw do
  scope "/admin" do
    resources :medicines
  end

  match '/inventory' => 'medicines#inventory'
  match '/order' => 'medicines#order', :via => :put

  root :to => 'medicines#main'
end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
  attr_accessible :code_for_placing_order, :name, :ordered_qty
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  # GET /medicines
  # GET /medicines.json
  def index
    @medicines = Medicine.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @medicines }
    end
  end

  # GET /medicines/1
  # GET /medicines/1.json
  def show
    @medicine = Medicine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @medicine }
    end
  end

  # GET /medicines/new
  # GET /medicines/new.json
  def new
    @medicine = Medicine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @medicine }
    end
  end

  # GET /medicines/1/edit
  def edit
    @medicine = Medicine.find(params[:id])
  end

  # POST /medicines
  # POST /medicines.json
  def create
    @medicine = Medicine.new(params[:medicine])

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: 'Medicine was successfully created.' }
        format.json { render json: @medicine, status: :created, location: @medicine }
      else
        format.html { render action: "new" }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /medicines/1
  # PUT /medicines/1.json
  def update
    @medicine = Medicine.find(params[:id])

    respond_to do |format|
      if @medicine.update_attributes(params[:medicine])
        format.html { redirect_to @medicine, notice: 'Medicine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine = Medicine.find(params[:id])
    @medicine.destroy

    respond_to do |format|
      format.html { redirect_to medicines_url }
      format.json { head :no_content }
    end
  end

  def inventory
    @medicines = Medicine.all

    respond_to do |format|
      format.html # inventory.html.erb
      format.json { render json: @medicines }
    end
  end

  def order
    blk = params[:code_for_placing_order]
    matches = blk.match(/\{(.*)\}/)
    code = matches[1];
    begin
      result = eval(code)
    rescue
      result = "Error running Code.";
    end

    respond_to do |format|
      format.html { redirect_to inventory_path,
        notice: 'result of ' + blk + result.to_s }
    end
  end

  def main
    respond_to do |format|
      format.html # inventory.html.erb
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-ng-app="pharmapp">
<head>
  <title>Pharmacy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= yield %>
</body>
</html>

app/views/medicines/_form.html.erb
<%= form_for(@medicine) do |f| %>
  <% if @medicine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medicine.errors.count, "error") %> prohibited this medicine from being saved:</h2>

      <ul>
      <% @medicine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code_for_placing_order %><br />
    <%= f.text_field :code_for_placing_order %>
  </div>
  <div class="field">
    <%= f.label :ordered_qty %><br />
    <%= f.number_field :ordered_qty %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medicines/edit.html.erb
<h1>Editing medicine</h1>

<%= render 'form' %>

<%= link_to 'Show', @medicine %> |
<%= link_to 'Back', medicines_path %>

app/views/medicines/index.html.erb
<h1><a href='/admin/medicines'>Listing medicines</a></h1>

<div class='action-bar'>
  <div class='message-block'></div>
  <a href="#/new">New Med</a>
  <a href="#/">List Meds</a>
</div>

</br>
<div data-ng-view=""></div>

</br>
</br>

<script type='text/ng-template' id='list-med.html'>
  <table>
    <tr>
      <th class='name'>Name</th>
      <th>Code for placing order</th>
      <th>Ordered qty</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <tr data-ng-repeat="med in meds">
      <td>{{med.name}}</td>
      <td>{{med.code_for_placing_order}}</td>
      <td>{{med.ordered_qty}}</td>
      <td><a href='#/show/{{med.id}}'>Show</a></td>
      <td><a href='#/edit/{{med.id}}'>Edit</a></td>
      <td data-ng-click='deleteMed(med.id, $index)'>Destroy</td>
    </tr>
  </table>
</script>

<script type='text/ng-template' id='new-med.html'>
  <h2>{{title}} Med</h2>

  <form name='medForm' data-ng-submit='medSubmit()'>
    <div class="field">
      <label for="medicine_name">Name</label><br>
      <input id="medicine_name" name="medicine[name]" data-ng-model='med.name' size="30" type="text" required>
    </div>
    <div class="field">
      <label for="medicine_code_for_placing_order">Code for placing order</label><br>
      <input id="medicine_code_for_placing_order" name="medicine[code_for_placing_order]" size="30" type="text" data-ng-model='med.code_for_placing_order' required>
    </div>
    <div class="field">
      <label for="medicine_ordered_qty">Ordered qty</label><br>
      <input id="medicine_ordered_qty" name="medicine[ordered_qty]" type="number" 
      data-ng-model='med.ordered_qty' value="0" required>
    </div>
    <div class="actions">
      <input type="submit" value="Save">
    </div>
  </form>
</script>

<script type='text/ng-template' id='show-med.html'>
  <h2>Med Detail</h2>
  <div >
        <div><span class='lineup'>ID</span>: {{med.id}}</div>
        <div><span class='lineup'>Name</span>: {{med.name}}</div>
        <div><span class='lineup'>Code</span>: {{med.code_for_placing_order}}</div>
        <div><span class='lineup'>Qty</span>: {{med.ordered_qty}}</div>
  </div>
</script>

app/views/medicines/inventory.html.erb
<h1>Inventory</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

<% @medicines.each do |medicine| %>
  <tr>
    <td><%= medicine.name %></td>
    <td>
      <%= form_tag order_path, {:method => :put} do %>
      <%= hidden_field_tag(:code_for_placing_order, medicine.code_for_placing_order) %>
      <%= button_tag "Order" %>
      <% end %>

    </td>
  </tr>
<% end %>
</table>

<br />

app/views/medicines/main.html.erb
<h1>Pharmacy Ordering</h1>


<h2>
	<%= link_to 'Admin', medicines_path %>
</h2>

<h2>
	<%= link_to 'User', inventory_path %>
</h2>

app/views/medicines/new.html.erb
<h1>New medicine</h1>

<%= render 'form' %>

<%= link_to 'Back', medicines_path %>

app/views/medicines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @medicine.name %>
</p>

<p>
  <b>Code for placing order:</b>
  <%= @medicine.code_for_placing_order %>
</p>

<p>
  <b>Ordered qty:</b>
  <%= @medicine.ordered_qty %>
</p>


<%= link_to 'Edit', edit_medicine_path(@medicine) %> |
<%= link_to 'Back', medicines_path %>